export type Customer = {
  id: string;
  name: string;
  email: string;
  phone: string;
  city: string;
  address: string;
  loyaltyPoints: number;
  totalSpent: number;
  notes: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  firstName: string;
  lastName: string;
  gender: string | null;
  birthDate: string | null;
  companyName: string | null;
  taxNumber: string | null;
  creditLimit: number;
  paymentTerms: string;
  preferredContact: string;
  vipStatus: string;
  totalOrders: number;
  lastOrderDate: string;
  country: string;
  postalCode: string;
  avatar: string;
  customerSince: string;
  status: string;
  preferredPaymentMethod: string;
  averageOrderValue: number;
};
